// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW1mvTVMaosOI1xj_vXDTFUW9G2CtLUWM',
    appId: '1:315231683982:web:4fc907aaa629fd67e6d0df',
    messagingSenderId: '315231683982',
    projectId: 'sollylabs-flutter',
    authDomain: 'sollylabs-flutter.firebaseapp.com',
    storageBucket: 'sollylabs-flutter.firebasestorage.app',
    measurementId: 'G-K5P06Q0DE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIqOeVFiOh_gA6Fz6Q53EcdCWJTYTH61A',
    appId: '1:315231683982:android:d33302cc700fedbfe6d0df',
    messagingSenderId: '315231683982',
    projectId: 'sollylabs-flutter',
    storageBucket: 'sollylabs-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR_sLQ9lTcrdykB6yy3yGlCBryL03LnkI',
    appId: '1:315231683982:ios:e94bde3dbedf3e47e6d0df',
    messagingSenderId: '315231683982',
    projectId: 'sollylabs-flutter',
    storageBucket: 'sollylabs-flutter.firebasestorage.app',
    iosBundleId: 'com.sollylabsflutter.sollylabsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR_sLQ9lTcrdykB6yy3yGlCBryL03LnkI',
    appId: '1:315231683982:ios:e94bde3dbedf3e47e6d0df',
    messagingSenderId: '315231683982',
    projectId: 'sollylabs-flutter',
    storageBucket: 'sollylabs-flutter.firebasestorage.app',
    iosBundleId: 'com.sollylabsflutter.sollylabsFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW1mvTVMaosOI1xj_vXDTFUW9G2CtLUWM',
    appId: '1:315231683982:web:ab0002b152feb963e6d0df',
    messagingSenderId: '315231683982',
    projectId: 'sollylabs-flutter',
    authDomain: 'sollylabs-flutter.firebaseapp.com',
    storageBucket: 'sollylabs-flutter.firebasestorage.app',
    measurementId: 'G-4PVWFYHWQ9',
  );
}
